export const API_ELEVATION_SVG: string =
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 771 1786" width="7'
    + '71" height="1786">\n  <defs>\n    <style>\n      .legend, .wing, .col'
    + ' { font-family:\n        ui-sans-serif, system-ui, sans-serif;\n     '
    + ' }\n      .legend { fill: hsl(217 38% 38%);\n        font-size: 11px;'
    + ' }\n      .wing { fill: hsl(217 45% 15%);\n        font-size: 12px; f'
    + 'ont-weight: 700; }\n      .col { fill: hsl(217 12% 40%);\n        fon'
    + 't-size: 8px; text-anchor: middle;\n      }\n      .uri { font-family:'
    + ' ui-monospace,\n        SFMono-Regular, Menlo, monospace;\n        fo'
    + 'nt-size: 8.5px;\n        fill: hsl(217 45% 15%); }\n      .filled { f'
    + 'ill: hsl(217 45% 15%); }\n      .empty { fill: none;\n        stroke:'
    + ' hsl(217 30% 40%);\n        stroke-width: 1; }\n    </style>\n  </def'
    + 's>\n  <rect x="0" y="0" width="771" height="1786" fill="hsl(217 30% 9'
    + '7%)"/>\n  <text class="legend" x="16" y="28">filled circle = offered '
    + 'verb (item or operation)</text>\n  <text class="col" x="34" y="50">GE'
    + 'T</text>\n  <text class="col" x="74" y="50">PUT</text>\n  <text class'
    + '="col" x="114" y="50">POST</text>\n  <text class="col" x="154" y="50"'
    + '>PATCH</text>\n  <text class="col" x="194" y="50">DELETE</text>\n  <t'
    + 'ext class="wing" x="16" y="72">ai-agents</text>\n  <a href="#get/ai-a'
    + 'gents">\n    <circle class="filled" cx="34" cy="88" r="5"/>\n  </a>\n'
    + '  <rect class="empty" x="69" y="83" width="10" height="10" fill="none'
    + '"/>\n  <rect class="empty" x="109" y="83" width="10" height="10" fill'
    + '="none"/>\n  <rect class="empty" x="149" y="83" width="10" height="10'
    + '" fill="none"/>\n  <rect class="empty" x="189" y="83" width="10" heig'
    + 'ht="10" fill="none"/>\n  <text class="uri" x="224" y="91">/api/ai-age'
    + 'nts/</text>\n  <a href="#get/ai-agents/id">\n    <circle class="fille'
    + 'd" cx="34" cy="106" r="5"/>\n  </a>\n  <a href="#put/ai-agents/id">\n'
    + '    <circle class="filled" cx="74" cy="106" r="5"/>\n  </a>\n  <rect '
    + 'class="empty" x="109" y="101" width="10" height="10" fill="none"/>\n '
    + ' <rect class="empty" x="149" y="101" width="10" height="10" fill="non'
    + 'e"/>\n  <rect class="empty" x="189" y="101" width="10" height="10" fi'
    + 'll="none"/>\n  <text class="uri" x="224" y="109">/api/ai-agents/:id</'
    + 'text>\n  <a href="#get/ai-agents/id/versions">\n    <circle class="fi'
    + 'lled" cx="34" cy="124" r="5"/>\n  </a>\n  <rect class="empty" x="69" '
    + 'y="119" width="10" height="10" fill="none"/>\n  <rect class="empty" x'
    + '="109" y="119" width="10" height="10" fill="none"/>\n  <rect class="e'
    + 'mpty" x="149" y="119" width="10" height="10" fill="none"/>\n  <rect c'
    + 'lass="empty" x="189" y="119" width="10" height="10" fill="none"/>\n  '
    + '<text class="uri" x="224" y="127">/api/ai-agents/:id/versions/</text>'
    + '\n  <a href="#get/ai-agents/id/versions/etag">\n    <circle class="fi'
    + 'lled" cx="34" cy="142" r="5"/>\n  </a>\n  <rect class="empty" x="69" '
    + 'y="137" width="10" height="10" fill="none"/>\n  <rect class="empty" x'
    + '="109" y="137" width="10" height="10" fill="none"/>\n  <rect class="e'
    + 'mpty" x="149" y="137" width="10" height="10" fill="none"/>\n  <rect c'
    + 'lass="empty" x="189" y="137" width="10" height="10" fill="none"/>\n  '
    + '<text class="uri" x="224" y="145">/api/ai-agents/:id/versions/:etag</'
    + 'text>\n  <text class="wing" x="16" y="174">authentication</text>\n  <'
    + 'rect class="empty" x="29" y="185" width="10" height="10" fill="none"/'
    + '>\n  <rect class="empty" x="69" y="185" width="10" height="10" fill="'
    + 'none"/>\n  <a href="#post/authentication/authorize">\n    <circle cla'
    + 'ss="filled" cx="114" cy="190" r="5"/>\n  </a>\n  <rect class="empty" '
    + 'x="149" y="185" width="10" height="10" fill="none"/>\n  <rect class="'
    + 'empty" x="189" y="185" width="10" height="10" fill="none"/>\n  <text '
    + 'class="uri" x="224" y="193">/api/authentication/authorize</text>\n  <'
    + 'rect class="empty" x="29" y="203" width="10" height="10" fill="none"/'
    + '>\n  <rect class="empty" x="69" y="203" width="10" height="10" fill="'
    + 'none"/>\n  <a href="#post/authentication/token">\n    <circle class="'
    + 'filled" cx="114" cy="208" r="5"/>\n  </a>\n  <rect class="empty" x="1'
    + '49" y="203" width="10" height="10" fill="none"/>\n  <rect class="empt'
    + 'y" x="189" y="203" width="10" height="10" fill="none"/>\n  <text clas'
    + 's="uri" x="224" y="211">/api/authentication/token</text>\n  <text cla'
    + 'ss="wing" x="16" y="240">identities</text>\n  <a href="#get/identitie'
    + 's">\n    <circle class="filled" cx="34" cy="256" r="5"/>\n  </a>\n  <'
    + 'rect class="empty" x="69" y="251" width="10" height="10" fill="none"/'
    + '>\n  <a href="#post/identities">\n    <circle class="filled" cx="114"'
    + ' cy="256" r="5"/>\n  </a>\n  <rect class="empty" x="149" y="251" widt'
    + 'h="10" height="10" fill="none"/>\n  <rect class="empty" x="189" y="25'
    + '1" width="10" height="10" fill="none"/>\n  <text class="uri" x="224" '
    + 'y="259">/api/identities/</text>\n  <a href="#get/identities/id">\n   '
    + ' <circle class="filled" cx="34" cy="274" r="5"/>\n  </a>\n  <a href="'
    + '#put/identities/id">\n    <circle class="filled" cx="74" cy="274" r="'
    + '5"/>\n  </a>\n  <rect class="empty" x="109" y="269" width="10" height'
    + '="10" fill="none"/>\n  <rect class="empty" x="149" y="269" width="10"'
    + ' height="10" fill="none"/>\n  <rect class="empty" x="189" y="269" wid'
    + 'th="10" height="10" fill="none"/>\n  <text class="uri" x="224" y="277'
    + '">/api/identities/:id</text>\n  <a href="#get/identities/id/credentia'
    + 'ls">\n    <circle class="filled" cx="34" cy="292" r="5"/>\n  </a>\n  '
    + '<rect class="empty" x="69" y="287" width="10" height="10" fill="none"'
    + '/>\n  <rect class="empty" x="109" y="287" width="10" height="10" fill'
    + '="none"/>\n  <rect class="empty" x="149" y="287" width="10" height="1'
    + '0" fill="none"/>\n  <rect class="empty" x="189" y="287" width="10" he'
    + 'ight="10" fill="none"/>\n  <text class="uri" x="224" y="295">/api/ide'
    + 'ntities/:id/credentials/</text>\n  <a href="#get/identities/id/creden'
    + 'tials/cid">\n    <circle class="filled" cx="34" cy="310" r="5"/>\n  <'
    + '/a>\n  <a href="#put/identities/id/credentials/cid">\n    <circle cla'
    + 'ss="filled" cx="74" cy="310" r="5"/>\n  </a>\n  <rect class="empty" x'
    + '="109" y="305" width="10" height="10" fill="none"/>\n  <rect class="e'
    + 'mpty" x="149" y="305" width="10" height="10" fill="none"/>\n  <rect c'
    + 'lass="empty" x="189" y="305" width="10" height="10" fill="none"/>\n  '
    + '<text class="uri" x="224" y="313">/api/identities/:id/credentials/:ci'
    + 'd</text>\n  <a href="#get/identities/id/default-organization">\n    <'
    + 'circle class="filled" cx="34" cy="328" r="5"/>\n  </a>\n  <a href="#p'
    + 'ut/identities/id/default-organization">\n    <circle class="filled" c'
    + 'x="74" cy="328" r="5"/>\n  </a>\n  <rect class="empty" x="109" y="323'
    + '" width="10" height="10" fill="none"/>\n  <rect class="empty" x="149"'
    + ' y="323" width="10" height="10" fill="none"/>\n  <rect class="empty" '
    + 'x="189" y="323" width="10" height="10" fill="none"/>\n  <text class="'
    + 'uri" x="224" y="331">/api/identities/:id/default-organization</text>'
    + '\n  <a href="#get/identities/id/invitations">\n    <circle class="fil'
    + 'led" cx="34" cy="346" r="5"/>\n  </a>\n  <rect class="empty" x="69" y'
    + '="341" width="10" height="10" fill="none"/>\n  <rect class="empty" x='
    + '"109" y="341" width="10" height="10" fill="none"/>\n  <rect class="em'
    + 'pty" x="149" y="341" width="10" height="10" fill="none"/>\n  <rect cl'
    + 'ass="empty" x="189" y="341" width="10" height="10" fill="none"/>\n  <'
    + 'text class="uri" x="224" y="349">/api/identities/:id/invitations/</te'
    + 'xt>\n  <a href="#get/identities/id/invitations/membership-id">\n    <'
    + 'circle class="filled" cx="34" cy="364" r="5"/>\n  </a>\n  <a href="#p'
    + 'ut/identities/id/invitations/membership-id">\n    <circle class="fill'
    + 'ed" cx="74" cy="364" r="5"/>\n  </a>\n  <rect class="empty" x="109" y'
    + '="359" width="10" height="10" fill="none"/>\n  <rect class="empty" x='
    + '"149" y="359" width="10" height="10" fill="none"/>\n  <rect class="em'
    + 'pty" x="189" y="359" width="10" height="10" fill="none"/>\n  <text cl'
    + 'ass="uri" x="224" y="367">/api/identities/:id/invitations/:membership'
    + '-id</text>\n  <a href="#get/identities/id/invitations/membership-id/v'
    + 'ersions">\n    <circle class="filled" cx="34" cy="382" r="5"/>\n  </a'
    + '>\n  <rect class="empty" x="69" y="377" width="10" height="10" fill="'
    + 'none"/>\n  <rect class="empty" x="109" y="377" width="10" height="10"'
    + ' fill="none"/>\n  <rect class="empty" x="149" y="377" width="10" heig'
    + 'ht="10" fill="none"/>\n  <rect class="empty" x="189" y="377" width="1'
    + '0" height="10" fill="none"/>\n  <text class="uri" x="224" y="385">/ap'
    + 'i/identities/:id/invitations/:membership-id/versions/</text>\n  <a hr'
    + 'ef="#get/identities/id/invitations/membership-id/versions/etag">\n   '
    + ' <circle class="filled" cx="34" cy="400" r="5"/>\n  </a>\n  <rect cla'
    + 'ss="empty" x="69" y="395" width="10" height="10" fill="none"/>\n  <re'
    + 'ct class="empty" x="109" y="395" width="10" height="10" fill="none"/>'
    + '\n  <rect class="empty" x="149" y="395" width="10" height="10" fill="'
    + 'none"/>\n  <rect class="empty" x="189" y="395" width="10" height="10"'
    + ' fill="none"/>\n  <text class="uri" x="224" y="403">/api/identities/:'
    + 'id/invitations/:membership-id/versions/:etag</text>\n  <a href="#get/'
    + 'identities/id/organizations">\n    <circle class="filled" cx="34" cy='
    + '"418" r="5"/>\n  </a>\n  <rect class="empty" x="69" y="413" width="10'
    + '" height="10" fill="none"/>\n  <rect class="empty" x="109" y="413" wi'
    + 'dth="10" height="10" fill="none"/>\n  <rect class="empty" x="149" y="'
    + '413" width="10" height="10" fill="none"/>\n  <rect class="empty" x="1'
    + '89" y="413" width="10" height="10" fill="none"/>\n  <text class="uri"'
    + ' x="224" y="421">/api/identities/:id/organizations/</text>\n  <a href'
    + '="#get/identities/id/pii">\n    <circle class="filled" cx="34" cy="43'
    + '6" r="5"/>\n  </a>\n  <a href="#put/identities/id/pii">\n    <circle '
    + 'class="filled" cx="74" cy="436" r="5"/>\n  </a>\n  <rect class="empty'
    + '" x="109" y="431" width="10" height="10" fill="none"/>\n  <rect class'
    + '="empty" x="149" y="431" width="10" height="10" fill="none"/>\n  <a h'
    + 'ref="#delete/identities/id/pii">\n    <circle class="filled" cx="194"'
    + ' cy="436" r="5"/>\n  </a>\n  <text class="uri" x="224" y="439">/api/i'
    + 'dentities/:id/pii</text>\n  <a href="#get/identities/id/providers">\n'
    + '    <circle class="filled" cx="34" cy="454" r="5"/>\n  </a>\n  <rect '
    + 'class="empty" x="69" y="449" width="10" height="10" fill="none"/>\n  '
    + '<rect class="empty" x="109" y="449" width="10" height="10" fill="none'
    + '"/>\n  <rect class="empty" x="149" y="449" width="10" height="10" fil'
    + 'l="none"/>\n  <rect class="empty" x="189" y="449" width="10" height="'
    + '10" fill="none"/>\n  <text class="uri" x="224" y="457">/api/identitie'
    + 's/:id/providers/</text>\n  <a href="#get/identities/id/providers/eid"'
    + '>\n    <circle class="filled" cx="34" cy="472" r="5"/>\n  </a>\n  <a '
    + 'href="#put/identities/id/providers/eid">\n    <circle class="filled" '
    + 'cx="74" cy="472" r="5"/>\n  </a>\n  <rect class="empty" x="109" y="46'
    + '7" width="10" height="10" fill="none"/>\n  <rect class="empty" x="149'
    + '" y="467" width="10" height="10" fill="none"/>\n  <rect class="empty"'
    + ' x="189" y="467" width="10" height="10" fill="none"/>\n  <text class='
    + '"uri" x="224" y="475">/api/identities/:id/providers/:eid</text>\n  <a'
    + ' href="#get/identities/id/registration">\n    <circle class="filled" '
    + 'cx="34" cy="490" r="5"/>\n  </a>\n  <a href="#put/identities/id/regis'
    + 'tration">\n    <circle class="filled" cx="74" cy="490" r="5"/>\n  </a'
    + '>\n  <rect class="empty" x="109" y="485" width="10" height="10" fill='
    + '"none"/>\n  <rect class="empty" x="149" y="485" width="10" height="10'
    + '" fill="none"/>\n  <a href="#delete/identities/id/registration">\n   '
    + ' <circle class="filled" cx="194" cy="490" r="5"/>\n  </a>\n  <text cl'
    + 'ass="uri" x="224" y="493">/api/identities/:id/registration</text>\n  '
    + '<a href="#get/identities/id/token-revocations/rid">\n    <circle clas'
    + 's="filled" cx="34" cy="508" r="5"/>\n  </a>\n  <a href="#put/identiti'
    + 'es/id/token-revocations/rid">\n    <circle class="filled" cx="74" cy='
    + '"508" r="5"/>\n  </a>\n  <rect class="empty" x="109" y="503" width="1'
    + '0" height="10" fill="none"/>\n  <rect class="empty" x="149" y="503" w'
    + 'idth="10" height="10" fill="none"/>\n  <rect class="empty" x="189" y='
    + '"503" width="10" height="10" fill="none"/>\n  <text class="uri" x="22'
    + '4" y="511">/api/identities/:id/token-revocations/:rid</text>\n  <a hr'
    + 'ef="#get/identities/id/tokens">\n    <circle class="filled" cx="34" c'
    + 'y="526" r="5"/>\n  </a>\n  <rect class="empty" x="69" y="521" width="'
    + '10" height="10" fill="none"/>\n  <rect class="empty" x="109" y="521" '
    + 'width="10" height="10" fill="none"/>\n  <rect class="empty" x="149" y'
    + '="521" width="10" height="10" fill="none"/>\n  <rect class="empty" x='
    + '"189" y="521" width="10" height="10" fill="none"/>\n  <text class="ur'
    + 'i" x="224" y="529">/api/identities/:id/tokens/</text>\n  <a href="#ge'
    + 't/identities/id/tokens/jti">\n    <circle class="filled" cx="34" cy="'
    + '544" r="5"/>\n  </a>\n  <a href="#put/identities/id/tokens/jti">\n   '
    + ' <circle class="filled" cx="74" cy="544" r="5"/>\n  </a>\n  <rect cla'
    + 'ss="empty" x="109" y="539" width="10" height="10" fill="none"/>\n  <r'
    + 'ect class="empty" x="149" y="539" width="10" height="10" fill="none"/'
    + '>\n  <rect class="empty" x="189" y="539" width="10" height="10" fill='
    + '"none"/>\n  <text class="uri" x="224" y="547">/api/identities/:id/tok'
    + 'ens/:jti</text>\n  <rect class="empty" x="29" y="557" width="10" heig'
    + 'ht="10" fill="none"/>\n  <rect class="empty" x="69" y="557" width="10'
    + '" height="10" fill="none"/>\n  <a href="#post/identities/id/tokens/jt'
    + 'i/revocation">\n    <circle class="filled" cx="114" cy="562" r="5"/>'
    + '\n  </a>\n  <rect class="empty" x="149" y="557" width="10" height="10'
    + '" fill="none"/>\n  <rect class="empty" x="189" y="557" width="10" hei'
    + 'ght="10" fill="none"/>\n  <text class="uri" x="224" y="565">/api/iden'
    + 'tities/:id/tokens/:jti/revocation</text>\n  <rect class="empty" x="29'
    + '" y="575" width="10" height="10" fill="none"/>\n  <rect class="empty"'
    + ' x="69" y="575" width="10" height="10" fill="none"/>\n  <a href="#pos'
    + 't/identities/id/tokens/jti/rotation">\n    <circle class="filled" cx='
    + '"114" cy="580" r="5"/>\n  </a>\n  <rect class="empty" x="149" y="575"'
    + ' width="10" height="10" fill="none"/>\n  <rect class="empty" x="189" '
    + 'y="575" width="10" height="10" fill="none"/>\n  <text class="uri" x="'
    + '224" y="583">/api/identities/:id/tokens/:jti/rotation</text>\n  <a hr'
    + 'ef="#get/identities/id/versions">\n    <circle class="filled" cx="34"'
    + ' cy="598" r="5"/>\n  </a>\n  <rect class="empty" x="69" y="593" width'
    + '="10" height="10" fill="none"/>\n  <rect class="empty" x="109" y="593'
    + '" width="10" height="10" fill="none"/>\n  <rect class="empty" x="149"'
    + ' y="593" width="10" height="10" fill="none"/>\n  <rect class="empty" '
    + 'x="189" y="593" width="10" height="10" fill="none"/>\n  <text class="'
    + 'uri" x="224" y="601">/api/identities/:id/versions/</text>\n  <a href='
    + '"#get/identities/id/versions/etag">\n    <circle class="filled" cx="3'
    + '4" cy="616" r="5"/>\n  </a>\n  <rect class="empty" x="69" y="611" wid'
    + 'th="10" height="10" fill="none"/>\n  <rect class="empty" x="109" y="6'
    + '11" width="10" height="10" fill="none"/>\n  <rect class="empty" x="14'
    + '9" y="611" width="10" height="10" fill="none"/>\n  <rect class="empty'
    + '" x="189" y="611" width="10" height="10" fill="none"/>\n  <text class'
    + '="uri" x="224" y="619">/api/identities/:id/versions/:etag</text>\n  <'
    + 'text class="wing" x="16" y="648">organizations</text>\n  <a href="#ge'
    + 't/organizations/id">\n    <circle class="filled" cx="34" cy="664" r="'
    + '5"/>\n  </a>\n  <a href="#put/organizations/id">\n    <circle class="'
    + 'filled" cx="74" cy="664" r="5"/>\n  </a>\n  <rect class="empty" x="10'
    + '9" y="659" width="10" height="10" fill="none"/>\n  <rect class="empty'
    + '" x="149" y="659" width="10" height="10" fill="none"/>\n  <rect class'
    + '="empty" x="189" y="659" width="10" height="10" fill="none"/>\n  <tex'
    + 't class="uri" x="224" y="667">/api/organizations/:id</text>\n  <a hre'
    + 'f="#get/organizations/id/flows">\n    <circle class="filled" cx="34" '
    + 'cy="682" r="5"/>\n  </a>\n  <rect class="empty" x="69" y="677" width='
    + '"10" height="10" fill="none"/>\n  <a href="#post/organizations/id/flo'
    + 'ws">\n    <circle class="filled" cx="114" cy="682" r="5"/>\n  </a>\n '
    + ' <rect class="empty" x="149" y="677" width="10" height="10" fill="non'
    + 'e"/>\n  <rect class="empty" x="189" y="677" width="10" height="10" fi'
    + 'll="none"/>\n  <text class="uri" x="224" y="685">/api/organizations/:'
    + 'id/flows/</text>\n  <a href="#get/organizations/id/flows/id">\n    <c'
    + 'ircle class="filled" cx="34" cy="700" r="5"/>\n  </a>\n  <a href="#pu'
    + 't/organizations/id/flows/id">\n    <circle class="filled" cx="74" cy='
    + '"700" r="5"/>\n  </a>\n  <rect class="empty" x="109" y="695" width="1'
    + '0" height="10" fill="none"/>\n  <rect class="empty" x="149" y="695" w'
    + 'idth="10" height="10" fill="none"/>\n  <rect class="empty" x="189" y='
    + '"695" width="10" height="10" fill="none"/>\n  <text class="uri" x="22'
    + '4" y="703">/api/organizations/:id/flows/:id</text>\n  <a href="#get/o'
    + 'rganizations/id/flows/id/records">\n    <circle class="filled" cx="34'
    + '" cy="718" r="5"/>\n  </a>\n  <rect class="empty" x="69" y="713" widt'
    + 'h="10" height="10" fill="none"/>\n  <rect class="empty" x="109" y="71'
    + '3" width="10" height="10" fill="none"/>\n  <rect class="empty" x="149'
    + '" y="713" width="10" height="10" fill="none"/>\n  <rect class="empty"'
    + ' x="189" y="713" width="10" height="10" fill="none"/>\n  <text class='
    + '"uri" x="224" y="721">/api/organizations/:id/flows/:id/records/</text'
    + '>\n  <a href="#get/organizations/id/flows/id/records/frid">\n    <cir'
    + 'cle class="filled" cx="34" cy="736" r="5"/>\n  </a>\n  <a href="#put/'
    + 'organizations/id/flows/id/records/frid">\n    <circle class="filled" '
    + 'cx="74" cy="736" r="5"/>\n  </a>\n  <rect class="empty" x="109" y="73'
    + '1" width="10" height="10" fill="none"/>\n  <rect class="empty" x="149'
    + '" y="731" width="10" height="10" fill="none"/>\n  <a href="#delete/or'
    + 'ganizations/id/flows/id/records/frid">\n    <circle class="filled" cx'
    + '="194" cy="736" r="5"/>\n  </a>\n  <text class="uri" x="224" y="739">'
    + '/api/organizations/:id/flows/:id/records/:frid</text>\n  <a href="#ge'
    + 't/organizations/id/flows/id/tags/name">\n    <circle class="filled" c'
    + 'x="34" cy="754" r="5"/>\n  </a>\n  <a href="#put/organizations/id/flo'
    + 'ws/id/tags/name">\n    <circle class="filled" cx="74" cy="754" r="5"/'
    + '>\n  </a>\n  <rect class="empty" x="109" y="749" width="10" height="1'
    + '0" fill="none"/>\n  <rect class="empty" x="149" y="749" width="10" he'
    + 'ight="10" fill="none"/>\n  <a href="#delete/organizations/id/flows/id'
    + '/tags/name">\n    <circle class="filled" cx="194" cy="754" r="5"/>\n '
    + ' </a>\n  <text class="uri" x="224" y="757">/api/organizations/:id/flo'
    + 'ws/:id/tags/:name</text>\n  <rect class="empty" x="29" y="767" width='
    + '"10" height="10" fill="none"/>\n  <rect class="empty" x="69" y="767" '
    + 'width="10" height="10" fill="none"/>\n  <a href="#post/organizations/'
    + 'id/flows/id/undo">\n    <circle class="filled" cx="114" cy="772" r="5'
    + '"/>\n  </a>\n  <rect class="empty" x="149" y="767" width="10" height='
    + '"10" fill="none"/>\n  <rect class="empty" x="189" y="767" width="10" '
    + 'height="10" fill="none"/>\n  <text class="uri" x="224" y="775">/api/o'
    + 'rganizations/:id/flows/:id/undo</text>\n  <a href="#get/organizations'
    + '/id/flows/id/versions">\n    <circle class="filled" cx="34" cy="790" '
    + 'r="5"/>\n  </a>\n  <rect class="empty" x="69" y="785" width="10" heig'
    + 'ht="10" fill="none"/>\n  <rect class="empty" x="109" y="785" width="1'
    + '0" height="10" fill="none"/>\n  <rect class="empty" x="149" y="785" w'
    + 'idth="10" height="10" fill="none"/>\n  <rect class="empty" x="189" y='
    + '"785" width="10" height="10" fill="none"/>\n  <text class="uri" x="22'
    + '4" y="793">/api/organizations/:id/flows/:id/versions/</text>\n  <a hr'
    + 'ef="#get/organizations/id/flows/id/versions/etag">\n    <circle class'
    + '="filled" cx="34" cy="808" r="5"/>\n  </a>\n  <rect class="empty" x="'
    + '69" y="803" width="10" height="10" fill="none"/>\n  <rect class="empt'
    + 'y" x="109" y="803" width="10" height="10" fill="none"/>\n  <rect clas'
    + 's="empty" x="149" y="803" width="10" height="10" fill="none"/>\n  <re'
    + 'ct class="empty" x="189" y="803" width="10" height="10" fill="none"/>'
    + '\n  <text class="uri" x="224" y="811">/api/organizations/:id/flows/:i'
    + 'd/versions/:etag</text>\n  <a href="#get/organizations/id/flows/id/wo'
    + 'rk-orders">\n    <circle class="filled" cx="34" cy="826" r="5"/>\n  <'
    + '/a>\n  <rect class="empty" x="69" y="821" width="10" height="10" fill'
    + '="none"/>\n  <rect class="empty" x="109" y="821" width="10" height="1'
    + '0" fill="none"/>\n  <rect class="empty" x="149" y="821" width="10" he'
    + 'ight="10" fill="none"/>\n  <rect class="empty" x="189" y="821" width='
    + '"10" height="10" fill="none"/>\n  <text class="uri" x="224" y="829">/'
    + 'api/organizations/:id/flows/:id/work-orders/</text>\n  <rect class="e'
    + 'mpty" x="29" y="839" width="10" height="10" fill="none"/>\n  <a href='
    + '"#put/organizations/id/flows/id/work-orders/woid">\n    <circle class'
    + '="filled" cx="74" cy="844" r="5"/>\n  </a>\n  <rect class="empty" x="'
    + '109" y="839" width="10" height="10" fill="none"/>\n  <rect class="emp'
    + 'ty" x="149" y="839" width="10" height="10" fill="none"/>\n  <rect cla'
    + 'ss="empty" x="189" y="839" width="10" height="10" fill="none"/>\n  <t'
    + 'ext class="uri" x="224" y="847">/api/organizations/:id/flows/:id/work'
    + '-orders/:woid</text>\n  <a href="#get/organizations/id/ideas">\n    <'
    + 'circle class="filled" cx="34" cy="862" r="5"/>\n  </a>\n  <rect class'
    + '="empty" x="69" y="857" width="10" height="10" fill="none"/>\n  <rect'
    + ' class="empty" x="109" y="857" width="10" height="10" fill="none"/>\n'
    + '  <rect class="empty" x="149" y="857" width="10" height="10" fill="no'
    + 'ne"/>\n  <rect class="empty" x="189" y="857" width="10" height="10" f'
    + 'ill="none"/>\n  <text class="uri" x="224" y="865">/api/organizations/'
    + ':id/ideas/</text>\n  <a href="#get/organizations/id/ideas/id">\n    <'
    + 'circle class="filled" cx="34" cy="880" r="5"/>\n  </a>\n  <a href="#p'
    + 'ut/organizations/id/ideas/id">\n    <circle class="filled" cx="74" cy'
    + '="880" r="5"/>\n  </a>\n  <rect class="empty" x="109" y="875" width="'
    + '10" height="10" fill="none"/>\n  <rect class="empty" x="149" y="875" '
    + 'width="10" height="10" fill="none"/>\n  <rect class="empty" x="189" y'
    + '="875" width="10" height="10" fill="none"/>\n  <text class="uri" x="2'
    + '24" y="883">/api/organizations/:id/ideas/:id</text>\n  <rect class="e'
    + 'mpty" x="29" y="893" width="10" height="10" fill="none"/>\n  <rect cl'
    + 'ass="empty" x="69" y="893" width="10" height="10" fill="none"/>\n  <a'
    + ' href="#post/organizations/id/ideas/id/conversion">\n    <circle clas'
    + 's="filled" cx="114" cy="898" r="5"/>\n  </a>\n  <rect class="empty" x'
    + '="149" y="893" width="10" height="10" fill="none"/>\n  <rect class="e'
    + 'mpty" x="189" y="893" width="10" height="10" fill="none"/>\n  <text c'
    + 'lass="uri" x="224" y="901">/api/organizations/:id/ideas/:id/conversio'
    + 'n</text>\n  <a href="#get/organizations/id/ideas/id/submissions">\n  '
    + '  <circle class="filled" cx="34" cy="916" r="5"/>\n  </a>\n  <rect cl'
    + 'ass="empty" x="69" y="911" width="10" height="10" fill="none"/>\n  <r'
    + 'ect class="empty" x="109" y="911" width="10" height="10" fill="none"/'
    + '>\n  <rect class="empty" x="149" y="911" width="10" height="10" fill='
    + '"none"/>\n  <rect class="empty" x="189" y="911" width="10" height="10'
    + '" fill="none"/>\n  <text class="uri" x="224" y="919">/api/organizatio'
    + 'ns/:id/ideas/:id/submissions/</text>\n  <rect class="empty" x="29" y='
    + '"929" width="10" height="10" fill="none"/>\n  <a href="#put/organizat'
    + 'ions/id/ideas/id/submissions/sid">\n    <circle class="filled" cx="74'
    + '" cy="934" r="5"/>\n  </a>\n  <rect class="empty" x="109" y="929" wid'
    + 'th="10" height="10" fill="none"/>\n  <rect class="empty" x="149" y="9'
    + '29" width="10" height="10" fill="none"/>\n  <rect class="empty" x="18'
    + '9" y="929" width="10" height="10" fill="none"/>\n  <text class="uri" '
    + 'x="224" y="937">/api/organizations/:id/ideas/:id/submissions/:sid</te'
    + 'xt>\n  <a href="#get/organizations/id/ideas/id/versions">\n    <circl'
    + 'e class="filled" cx="34" cy="952" r="5"/>\n  </a>\n  <rect class="emp'
    + 'ty" x="69" y="947" width="10" height="10" fill="none"/>\n  <rect clas'
    + 's="empty" x="109" y="947" width="10" height="10" fill="none"/>\n  <re'
    + 'ct class="empty" x="149" y="947" width="10" height="10" fill="none"/>'
    + '\n  <rect class="empty" x="189" y="947" width="10" height="10" fill="'
    + 'none"/>\n  <text class="uri" x="224" y="955">/api/organizations/:id/i'
    + 'deas/:id/versions/</text>\n  <a href="#get/organizations/id/ideas/id/'
    + 'versions/etag">\n    <circle class="filled" cx="34" cy="970" r="5"/>'
    + '\n  </a>\n  <rect class="empty" x="69" y="965" width="10" height="10"'
    + ' fill="none"/>\n  <rect class="empty" x="109" y="965" width="10" heig'
    + 'ht="10" fill="none"/>\n  <rect class="empty" x="149" y="965" width="1'
    + '0" height="10" fill="none"/>\n  <rect class="empty" x="189" y="965" w'
    + 'idth="10" height="10" fill="none"/>\n  <text class="uri" x="224" y="9'
    + '73">/api/organizations/:id/ideas/:id/versions/:etag</text>\n  <a href'
    + '="#get/organizations/id/invitations">\n    <circle class="filled" cx='
    + '"34" cy="988" r="5"/>\n  </a>\n  <rect class="empty" x="69" y="983" w'
    + 'idth="10" height="10" fill="none"/>\n  <a href="#post/organizations/i'
    + 'd/invitations">\n    <circle class="filled" cx="114" cy="988" r="5"/>'
    + '\n  </a>\n  <rect class="empty" x="149" y="983" width="10" height="10'
    + '" fill="none"/>\n  <rect class="empty" x="189" y="983" width="10" hei'
    + 'ght="10" fill="none"/>\n  <text class="uri" x="224" y="991">/api/orga'
    + 'nizations/:id/invitations/</text>\n  <a href="#get/organizations/id/i'
    + 'nvitations/membership-id">\n    <circle class="filled" cx="34" cy="10'
    + '06" r="5"/>\n  </a>\n  <a href="#put/organizations/id/invitations/mem'
    + 'bership-id">\n    <circle class="filled" cx="74" cy="1006" r="5"/>\n '
    + ' </a>\n  <rect class="empty" x="109" y="1001" width="10" height="10" '
    + 'fill="none"/>\n  <rect class="empty" x="149" y="1001" width="10" heig'
    + 'ht="10" fill="none"/>\n  <rect class="empty" x="189" y="1001" width="'
    + '10" height="10" fill="none"/>\n  <text class="uri" x="224" y="1009">/'
    + 'api/organizations/:id/invitations/:membership-id</text>\n  <a href="#'
    + 'get/organizations/id/invitations/membership-id/versions">\n    <circl'
    + 'e class="filled" cx="34" cy="1024" r="5"/>\n  </a>\n  <rect class="em'
    + 'pty" x="69" y="1019" width="10" height="10" fill="none"/>\n  <rect cl'
    + 'ass="empty" x="109" y="1019" width="10" height="10" fill="none"/>\n  '
    + '<rect class="empty" x="149" y="1019" width="10" height="10" fill="non'
    + 'e"/>\n  <rect class="empty" x="189" y="1019" width="10" height="10" f'
    + 'ill="none"/>\n  <text class="uri" x="224" y="1027">/api/organizations'
    + '/:id/invitations/:membership-id/versions/</text>\n  <a href="#get/org'
    + 'anizations/id/invitations/membership-id/versions/etag">\n    <circle '
    + 'class="filled" cx="34" cy="1042" r="5"/>\n  </a>\n  <rect class="empt'
    + 'y" x="69" y="1037" width="10" height="10" fill="none"/>\n  <rect clas'
    + 's="empty" x="109" y="1037" width="10" height="10" fill="none"/>\n  <r'
    + 'ect class="empty" x="149" y="1037" width="10" height="10" fill="none"'
    + '/>\n  <rect class="empty" x="189" y="1037" width="10" height="10" fil'
    + 'l="none"/>\n  <text class="uri" x="224" y="1045">/api/organizations/:'
    + 'id/invitations/:membership-id/versions/:etag</text>\n  <a href="#get/'
    + 'organizations/id/objectives">\n    <circle class="filled" cx="34" cy='
    + '"1060" r="5"/>\n  </a>\n  <rect class="empty" x="69" y="1055" width="'
    + '10" height="10" fill="none"/>\n  <a href="#post/organizations/id/obje'
    + 'ctives">\n    <circle class="filled" cx="114" cy="1060" r="5"/>\n  </'
    + 'a>\n  <rect class="empty" x="149" y="1055" width="10" height="10" fil'
    + 'l="none"/>\n  <rect class="empty" x="189" y="1055" width="10" height='
    + '"10" fill="none"/>\n  <text class="uri" x="224" y="1063">/api/organiz'
    + 'ations/:id/objectives/</text>\n  <a href="#get/organizations/id/objec'
    + 'tives/id">\n    <circle class="filled" cx="34" cy="1078" r="5"/>\n  <'
    + '/a>\n  <a href="#put/organizations/id/objectives/id">\n    <circle cl'
    + 'ass="filled" cx="74" cy="1078" r="5"/>\n  </a>\n  <rect class="empty"'
    + ' x="109" y="1073" width="10" height="10" fill="none"/>\n  <rect class'
    + '="empty" x="149" y="1073" width="10" height="10" fill="none"/>\n  <re'
    + 'ct class="empty" x="189" y="1073" width="10" height="10" fill="none"/'
    + '>\n  <text class="uri" x="224" y="1081">/api/organizations/:id/object'
    + 'ives/:id</text>\n  <a href="#get/organizations/id/objectives/id/revis'
    + 'ions">\n    <circle class="filled" cx="34" cy="1096" r="5"/>\n  </a>'
    + '\n  <rect class="empty" x="69" y="1091" width="10" height="10" fill="'
    + 'none"/>\n  <rect class="empty" x="109" y="1091" width="10" height="10'
    + '" fill="none"/>\n  <rect class="empty" x="149" y="1091" width="10" he'
    + 'ight="10" fill="none"/>\n  <rect class="empty" x="189" y="1091" width'
    + '="10" height="10" fill="none"/>\n  <text class="uri" x="224" y="1099"'
    + '>/api/organizations/:id/objectives/:id/revisions/</text>\n  <rect cla'
    + 'ss="empty" x="29" y="1109" width="10" height="10" fill="none"/>\n  <a'
    + ' href="#put/organizations/id/objectives/id/revisions/rid">\n    <circ'
    + 'le class="filled" cx="74" cy="1114" r="5"/>\n  </a>\n  <rect class="e'
    + 'mpty" x="109" y="1109" width="10" height="10" fill="none"/>\n  <rect '
    + 'class="empty" x="149" y="1109" width="10" height="10" fill="none"/>\n'
    + '  <rect class="empty" x="189" y="1109" width="10" height="10" fill="n'
    + 'one"/>\n  <text class="uri" x="224" y="1117">/api/organizations/:id/o'
    + 'bjectives/:id/revisions/:rid</text>\n  <a href="#get/organizations/id'
    + '/objectives/id/versions">\n    <circle class="filled" cx="34" cy="113'
    + '2" r="5"/>\n  </a>\n  <rect class="empty" x="69" y="1127" width="10" '
    + 'height="10" fill="none"/>\n  <rect class="empty" x="109" y="1127" wid'
    + 'th="10" height="10" fill="none"/>\n  <rect class="empty" x="149" y="1'
    + '127" width="10" height="10" fill="none"/>\n  <rect class="empty" x="1'
    + '89" y="1127" width="10" height="10" fill="none"/>\n  <text class="uri'
    + '" x="224" y="1135">/api/organizations/:id/objectives/:id/versions/</t'
    + 'ext>\n  <a href="#get/organizations/id/objectives/id/versions/etag">'
    + '\n    <circle class="filled" cx="34" cy="1150" r="5"/>\n  </a>\n  <re'
    + 'ct class="empty" x="69" y="1145" width="10" height="10" fill="none"/>'
    + '\n  <rect class="empty" x="109" y="1145" width="10" height="10" fill='
    + '"none"/>\n  <rect class="empty" x="149" y="1145" width="10" height="1'
    + '0" fill="none"/>\n  <rect class="empty" x="189" y="1145" width="10" h'
    + 'eight="10" fill="none"/>\n  <text class="uri" x="224" y="1153">/api/o'
    + 'rganizations/:id/objectives/:id/versions/:etag</text>\n  <a href="#ge'
    + 't/organizations/id/projects">\n    <circle class="filled" cx="34" cy='
    + '"1168" r="5"/>\n  </a>\n  <rect class="empty" x="69" y="1163" width="'
    + '10" height="10" fill="none"/>\n  <rect class="empty" x="109" y="1163"'
    + ' width="10" height="10" fill="none"/>\n  <rect class="empty" x="149" '
    + 'y="1163" width="10" height="10" fill="none"/>\n  <rect class="empty" '
    + 'x="189" y="1163" width="10" height="10" fill="none"/>\n  <text class='
    + '"uri" x="224" y="1171">/api/organizations/:id/projects/</text>\n  <a '
    + 'href="#get/organizations/id/projects/id">\n    <circle class="filled"'
    + ' cx="34" cy="1186" r="5"/>\n  </a>\n  <a href="#put/organizations/id/'
    + 'projects/id">\n    <circle class="filled" cx="74" cy="1186" r="5"/>\n'
    + '  </a>\n  <rect class="empty" x="109" y="1181" width="10" height="10"'
    + ' fill="none"/>\n  <rect class="empty" x="149" y="1181" width="10" hei'
    + 'ght="10" fill="none"/>\n  <rect class="empty" x="189" y="1181" width='
    + '"10" height="10" fill="none"/>\n  <text class="uri" x="224" y="1189">'
    + '/api/organizations/:id/projects/:id</text>\n  <a href="#get/organizat'
    + 'ions/id/projects/id/flows">\n    <circle class="filled" cx="34" cy="1'
    + '204" r="5"/>\n  </a>\n  <rect class="empty" x="69" y="1199" width="10'
    + '" height="10" fill="none"/>\n  <rect class="empty" x="109" y="1199" w'
    + 'idth="10" height="10" fill="none"/>\n  <rect class="empty" x="149" y='
    + '"1199" width="10" height="10" fill="none"/>\n  <rect class="empty" x='
    + '"189" y="1199" width="10" height="10" fill="none"/>\n  <text class="u'
    + 'ri" x="224" y="1207">/api/organizations/:id/projects/:id/flows/</text'
    + '>\n  <rect class="empty" x="29" y="1217" width="10" height="10" fill='
    + '"none"/>\n  <a href="#put/organizations/id/projects/id/flows/pfid">\n'
    + '    <circle class="filled" cx="74" cy="1222" r="5"/>\n  </a>\n  <rect'
    + ' class="empty" x="109" y="1217" width="10" height="10" fill="none"/>'
    + '\n  <rect class="empty" x="149" y="1217" width="10" height="10" fill='
    + '"none"/>\n  <a href="#delete/organizations/id/projects/id/flows/pfid"'
    + '>\n    <circle class="filled" cx="194" cy="1222" r="5"/>\n  </a>\n  <'
    + 'text class="uri" x="224" y="1225">/api/organizations/:id/projects/:id'
    + '/flows/:pfid</text>\n  <a href="#get/organizations/id/projects/id/obj'
    + 'ective-actual-scores">\n    <circle class="filled" cx="34" cy="1240" '
    + 'r="5"/>\n  </a>\n  <rect class="empty" x="69" y="1235" width="10" hei'
    + 'ght="10" fill="none"/>\n  <rect class="empty" x="109" y="1235" width='
    + '"10" height="10" fill="none"/>\n  <rect class="empty" x="149" y="1235'
    + '" width="10" height="10" fill="none"/>\n  <rect class="empty" x="189"'
    + ' y="1235" width="10" height="10" fill="none"/>\n  <text class="uri" x'
    + '="224" y="1243">/api/organizations/:id/projects/:id/objective-actual-'
    + 'scores/</text>\n  <rect class="empty" x="29" y="1253" width="10" heig'
    + 'ht="10" fill="none"/>\n  <a href="#put/organizations/id/projects/id/o'
    + 'bjective-actual-scores/sid">\n    <circle class="filled" cx="74" cy="'
    + '1258" r="5"/>\n  </a>\n  <rect class="empty" x="109" y="1253" width="'
    + '10" height="10" fill="none"/>\n  <rect class="empty" x="149" y="1253"'
    + ' width="10" height="10" fill="none"/>\n  <rect class="empty" x="189" '
    + 'y="1253" width="10" height="10" fill="none"/>\n  <text class="uri" x='
    + '"224" y="1261">/api/organizations/:id/projects/:id/objective-actual-s'
    + 'cores/:sid</text>\n  <a href="#get/organizations/id/projects/id/objec'
    + 'tive-baseline-scores">\n    <circle class="filled" cx="34" cy="1276" '
    + 'r="5"/>\n  </a>\n  <rect class="empty" x="69" y="1271" width="10" hei'
    + 'ght="10" fill="none"/>\n  <rect class="empty" x="109" y="1271" width='
    + '"10" height="10" fill="none"/>\n  <rect class="empty" x="149" y="1271'
    + '" width="10" height="10" fill="none"/>\n  <rect class="empty" x="189"'
    + ' y="1271" width="10" height="10" fill="none"/>\n  <text class="uri" x'
    + '="224" y="1279">/api/organizations/:id/projects/:id/objective-baselin'
    + 'e-scores/</text>\n  <rect class="empty" x="29" y="1289" width="10" he'
    + 'ight="10" fill="none"/>\n  <a href="#put/organizations/id/projects/id'
    + '/objective-baseline-scores/sid">\n    <circle class="filled" cx="74" '
    + 'cy="1294" r="5"/>\n  </a>\n  <rect class="empty" x="109" y="1289" wid'
    + 'th="10" height="10" fill="none"/>\n  <rect class="empty" x="149" y="1'
    + '289" width="10" height="10" fill="none"/>\n  <rect class="empty" x="1'
    + '89" y="1289" width="10" height="10" fill="none"/>\n  <text class="uri'
    + '" x="224" y="1297">/api/organizations/:id/projects/:id/objective-base'
    + 'line-scores/:sid</text>\n  <a href="#get/organizations/id/projects/id'
    + '/versions">\n    <circle class="filled" cx="34" cy="1312" r="5"/>\n  '
    + '</a>\n  <rect class="empty" x="69" y="1307" width="10" height="10" fi'
    + 'll="none"/>\n  <rect class="empty" x="109" y="1307" width="10" height'
    + '="10" fill="none"/>\n  <rect class="empty" x="149" y="1307" width="10'
    + '" height="10" fill="none"/>\n  <rect class="empty" x="189" y="1307" w'
    + 'idth="10" height="10" fill="none"/>\n  <text class="uri" x="224" y="1'
    + '315">/api/organizations/:id/projects/:id/versions/</text>\n  <a href='
    + '"#get/organizations/id/projects/id/versions/etag">\n    <circle class'
    + '="filled" cx="34" cy="1330" r="5"/>\n  </a>\n  <rect class="empty" x='
    + '"69" y="1325" width="10" height="10" fill="none"/>\n  <rect class="em'
    + 'pty" x="109" y="1325" width="10" height="10" fill="none"/>\n  <rect c'
    + 'lass="empty" x="149" y="1325" width="10" height="10" fill="none"/>\n '
    + ' <rect class="empty" x="189" y="1325" width="10" height="10" fill="no'
    + 'ne"/>\n  <text class="uri" x="224" y="1333">/api/organizations/:id/pr'
    + 'ojects/:id/versions/:etag</text>\n  <a href="#get/organizations/id/ve'
    + 'rsions">\n    <circle class="filled" cx="34" cy="1348" r="5"/>\n  </a'
    + '>\n  <rect class="empty" x="69" y="1343" width="10" height="10" fill='
    + '"none"/>\n  <rect class="empty" x="109" y="1343" width="10" height="1'
    + '0" fill="none"/>\n  <rect class="empty" x="149" y="1343" width="10" h'
    + 'eight="10" fill="none"/>\n  <rect class="empty" x="189" y="1343" widt'
    + 'h="10" height="10" fill="none"/>\n  <text class="uri" x="224" y="1351'
    + '">/api/organizations/:id/versions/</text>\n  <a href="#get/organizati'
    + 'ons/id/versions/etag">\n    <circle class="filled" cx="34" cy="1366" '
    + 'r="5"/>\n  </a>\n  <rect class="empty" x="69" y="1361" width="10" hei'
    + 'ght="10" fill="none"/>\n  <rect class="empty" x="109" y="1361" width='
    + '"10" height="10" fill="none"/>\n  <rect class="empty" x="149" y="1361'
    + '" width="10" height="10" fill="none"/>\n  <rect class="empty" x="189"'
    + ' y="1361" width="10" height="10" fill="none"/>\n  <text class="uri" x'
    + '="224" y="1369">/api/organizations/:id/versions/:etag</text>\n  <a hr'
    + 'ef="#get/organizations/id/work-orders">\n    <circle class="filled" c'
    + 'x="34" cy="1384" r="5"/>\n  </a>\n  <rect class="empty" x="69" y="137'
    + '9" width="10" height="10" fill="none"/>\n  <a href="#post/organizatio'
    + 'ns/id/work-orders">\n    <circle class="filled" cx="114" cy="1384" r='
    + '"5"/>\n  </a>\n  <rect class="empty" x="149" y="1379" width="10" heig'
    + 'ht="10" fill="none"/>\n  <rect class="empty" x="189" y="1379" width="'
    + '10" height="10" fill="none"/>\n  <text class="uri" x="224" y="1387">/'
    + 'api/organizations/:id/work-orders/</text>\n  <a href="#get/organizati'
    + 'ons/id/work-orders/id">\n    <circle class="filled" cx="34" cy="1402"'
    + ' r="5"/>\n  </a>\n  <a href="#put/organizations/id/work-orders/id">\n'
    + '    <circle class="filled" cx="74" cy="1402" r="5"/>\n  </a>\n  <rect'
    + ' class="empty" x="109" y="1397" width="10" height="10" fill="none"/>'
    + '\n  <rect class="empty" x="149" y="1397" width="10" height="10" fill='
    + '"none"/>\n  <rect class="empty" x="189" y="1397" width="10" height="1'
    + '0" fill="none"/>\n  <text class="uri" x="224" y="1405">/api/organizat'
    + 'ions/:id/work-orders/:id</text>\n  <rect class="empty" x="29" y="1415'
    + '" width="10" height="10" fill="none"/>\n  <a href="#put/organizations'
    + '/id/work-orders/id/binding">\n    <circle class="filled" cx="74" cy="'
    + '1420" r="5"/>\n  </a>\n  <rect class="empty" x="109" y="1415" width="'
    + '10" height="10" fill="none"/>\n  <rect class="empty" x="149" y="1415"'
    + ' width="10" height="10" fill="none"/>\n  <rect class="empty" x="189" '
    + 'y="1415" width="10" height="10" fill="none"/>\n  <text class="uri" x='
    + '"224" y="1423">/api/organizations/:id/work-orders/:id/binding</text>'
    + '\n  <rect class="empty" x="29" y="1433" width="10" height="10" fill="'
    + 'none"/>\n  <a href="#put/organizations/id/work-orders/id/claim">\n   '
    + ' <circle class="filled" cx="74" cy="1438" r="5"/>\n  </a>\n  <rect cl'
    + 'ass="empty" x="109" y="1433" width="10" height="10" fill="none"/>\n  '
    + '<rect class="empty" x="149" y="1433" width="10" height="10" fill="non'
    + 'e"/>\n  <a href="#delete/organizations/id/work-orders/id/claim">\n   '
    + ' <circle class="filled" cx="194" cy="1438" r="5"/>\n  </a>\n  <text c'
    + 'lass="uri" x="224" y="1441">/api/organizations/:id/work-orders/:id/cl'
    + 'aim</text>\n  <a href="#get/organizations/id/work-orders/id/history">'
    + '\n    <circle class="filled" cx="34" cy="1456" r="5"/>\n  </a>\n  <re'
    + 'ct class="empty" x="69" y="1451" width="10" height="10" fill="none"/>'
    + '\n  <rect class="empty" x="109" y="1451" width="10" height="10" fill='
    + '"none"/>\n  <rect class="empty" x="149" y="1451" width="10" height="1'
    + '0" fill="none"/>\n  <rect class="empty" x="189" y="1451" width="10" h'
    + 'eight="10" fill="none"/>\n  <text class="uri" x="224" y="1459">/api/o'
    + 'rganizations/:id/work-orders/:id/history</text>\n  <rect class="empty'
    + '" x="29" y="1469" width="10" height="10" fill="none"/>\n  <rect class'
    + '="empty" x="69" y="1469" width="10" height="10" fill="none"/>\n  <a h'
    + 'ref="#post/organizations/id/work-orders/id/transition">\n    <circle '
    + 'class="filled" cx="114" cy="1474" r="5"/>\n  </a>\n  <rect class="emp'
    + 'ty" x="149" y="1469" width="10" height="10" fill="none"/>\n  <rect cl'
    + 'ass="empty" x="189" y="1469" width="10" height="10" fill="none"/>\n  '
    + '<text class="uri" x="224" y="1477">/api/organizations/:id/work-orders'
    + '/:id/transition</text>\n  <a href="#get/organizations/organization-id'
    + '/former-members">\n    <circle class="filled" cx="34" cy="1492" r="5"'
    + '/>\n  </a>\n  <rect class="empty" x="69" y="1487" width="10" height="'
    + '10" fill="none"/>\n  <rect class="empty" x="109" y="1487" width="10" '
    + 'height="10" fill="none"/>\n  <rect class="empty" x="149" y="1487" wid'
    + 'th="10" height="10" fill="none"/>\n  <rect class="empty" x="189" y="1'
    + '487" width="10" height="10" fill="none"/>\n  <text class="uri" x="224'
    + '" y="1495">/api/organizations/:organization-id/former-members/</text>'
    + '\n  <a href="#get/organizations/organization-id/members">\n    <circl'
    + 'e class="filled" cx="34" cy="1510" r="5"/>\n  </a>\n  <rect class="em'
    + 'pty" x="69" y="1505" width="10" height="10" fill="none"/>\n  <rect cl'
    + 'ass="empty" x="109" y="1505" width="10" height="10" fill="none"/>\n  '
    + '<rect class="empty" x="149" y="1505" width="10" height="10" fill="non'
    + 'e"/>\n  <rect class="empty" x="189" y="1505" width="10" height="10" f'
    + 'ill="none"/>\n  <text class="uri" x="224" y="1513">/api/organizations'
    + '/:organization-id/members/</text>\n  <a href="#get/organizations/orga'
    + 'nization-id/members/identity-id">\n    <circle class="filled" cx="34"'
    + ' cy="1528" r="5"/>\n  </a>\n  <a href="#put/organizations/organizatio'
    + 'n-id/members/identity-id">\n    <circle class="filled" cx="74" cy="15'
    + '28" r="5"/>\n  </a>\n  <rect class="empty" x="109" y="1523" width="10'
    + '" height="10" fill="none"/>\n  <rect class="empty" x="149" y="1523" w'
    + 'idth="10" height="10" fill="none"/>\n  <a href="#delete/organizations'
    + '/organization-id/members/identity-id">\n    <circle class="filled" cx'
    + '="194" cy="1528" r="5"/>\n  </a>\n  <text class="uri" x="224" y="1531'
    + '">/api/organizations/:organization-id/members/:identity-id</text>\n  '
    + '<a href="#get/organizations/organization-id/members/identity-id/versi'
    + 'ons">\n    <circle class="filled" cx="34" cy="1546" r="5"/>\n  </a>\n'
    + '  <rect class="empty" x="69" y="1541" width="10" height="10" fill="no'
    + 'ne"/>\n  <rect class="empty" x="109" y="1541" width="10" height="10" '
    + 'fill="none"/>\n  <rect class="empty" x="149" y="1541" width="10" heig'
    + 'ht="10" fill="none"/>\n  <rect class="empty" x="189" y="1541" width="'
    + '10" height="10" fill="none"/>\n  <text class="uri" x="224" y="1549">/'
    + 'api/organizations/:organization-id/members/:identity-id/versions/</te'
    + 'xt>\n  <a href="#get/organizations/organization-id/members/identity-i'
    + 'd/versions/etag">\n    <circle class="filled" cx="34" cy="1564" r="5"'
    + '/>\n  </a>\n  <rect class="empty" x="69" y="1559" width="10" height="'
    + '10" fill="none"/>\n  <rect class="empty" x="109" y="1559" width="10" '
    + 'height="10" fill="none"/>\n  <rect class="empty" x="149" y="1559" wid'
    + 'th="10" height="10" fill="none"/>\n  <rect class="empty" x="189" y="1'
    + '559" width="10" height="10" fill="none"/>\n  <text class="uri" x="224'
    + '" y="1567">/api/organizations/:organization-id/members/:identity-id/v'
    + 'ersions/:etag</text>\n  <a href="#get/organizations/organization-id/r'
    + 'ecord-types">\n    <circle class="filled" cx="34" cy="1582" r="5"/>\n'
    + '  </a>\n  <rect class="empty" x="69" y="1577" width="10" height="10" '
    + 'fill="none"/>\n  <a href="#post/organizations/organization-id/record-'
    + 'types">\n    <circle class="filled" cx="114" cy="1582" r="5"/>\n  </a'
    + '>\n  <rect class="empty" x="149" y="1577" width="10" height="10" fill'
    + '="none"/>\n  <rect class="empty" x="189" y="1577" width="10" height="'
    + '10" fill="none"/>\n  <text class="uri" x="224" y="1585">/api/organiza'
    + 'tions/:organization-id/record-types/</text>\n  <a href="#get/organiza'
    + 'tions/organization-id/record-types/record-type-id">\n    <circle clas'
    + 's="filled" cx="34" cy="1600" r="5"/>\n  </a>\n  <a href="#put/organiz'
    + 'ations/organization-id/record-types/record-type-id">\n    <circle cla'
    + 'ss="filled" cx="74" cy="1600" r="5"/>\n  </a>\n  <rect class="empty" '
    + 'x="109" y="1595" width="10" height="10" fill="none"/>\n  <rect class='
    + '"empty" x="149" y="1595" width="10" height="10" fill="none"/>\n  <a h'
    + 'ref="#delete/organizations/organization-id/record-types/record-type-i'
    + 'd">\n    <circle class="filled" cx="194" cy="1600" r="5"/>\n  </a>\n '
    + ' <text class="uri" x="224" y="1603">/api/organizations/:organization-'
    + 'id/record-types/:record-type-id</text>\n  <a href="#get/organizations'
    + '/organization-id/record-types/record-type-id/attributes">\n    <circl'
    + 'e class="filled" cx="34" cy="1618" r="5"/>\n  </a>\n  <rect class="em'
    + 'pty" x="69" y="1613" width="10" height="10" fill="none"/>\n  <rect cl'
    + 'ass="empty" x="109" y="1613" width="10" height="10" fill="none"/>\n  '
    + '<rect class="empty" x="149" y="1613" width="10" height="10" fill="non'
    + 'e"/>\n  <rect class="empty" x="189" y="1613" width="10" height="10" f'
    + 'ill="none"/>\n  <text class="uri" x="224" y="1621">/api/organizations'
    + '/:organization-id/record-types/:record-type-id/attributes/</text>\n  '
    + '<a href="#get/organizations/organization-id/record-types/record-type-'
    + 'id/attributes/attribute-id">\n    <circle class="filled" cx="34" cy="'
    + '1636" r="5"/>\n  </a>\n  <a href="#put/organizations/organization-id/'
    + 'record-types/record-type-id/attributes/attribute-id">\n    <circle cl'
    + 'ass="filled" cx="74" cy="1636" r="5"/>\n  </a>\n  <rect class="empty"'
    + ' x="109" y="1631" width="10" height="10" fill="none"/>\n  <rect class'
    + '="empty" x="149" y="1631" width="10" height="10" fill="none"/>\n  <a '
    + 'href="#delete/organizations/organization-id/record-types/record-type-'
    + 'id/attributes/attribute-id">\n    <circle class="filled" cx="194" cy='
    + '"1636" r="5"/>\n  </a>\n  <text class="uri" x="224" y="1639">/api/org'
    + 'anizations/:organization-id/record-types/:record-type-id/attributes/:'
    + 'attribute-id</text>\n  <a href="#get/organizations/organization-id/re'
    + 'cord-types/record-type-id/instances">\n    <circle class="filled" cx='
    + '"34" cy="1654" r="5"/>\n  </a>\n  <rect class="empty" x="69" y="1649"'
    + ' width="10" height="10" fill="none"/>\n  <rect class="empty" x="109" '
    + 'y="1649" width="10" height="10" fill="none"/>\n  <rect class="empty" '
    + 'x="149" y="1649" width="10" height="10" fill="none"/>\n  <rect class='
    + '"empty" x="189" y="1649" width="10" height="10" fill="none"/>\n  <tex'
    + 't class="uri" x="224" y="1657">/api/organizations/:organization-id/re'
    + 'cord-types/:record-type-id/instances/</text>\n  <a href="#get/organiz'
    + 'ations/organization-id/record-types/record-type-id/instances/instance'
    + '-id">\n    <circle class="filled" cx="34" cy="1672" r="5"/>\n  </a>\n'
    + '  <rect class="empty" x="69" y="1667" width="10" height="10" fill="no'
    + 'ne"/>\n  <rect class="empty" x="109" y="1667" width="10" height="10" '
    + 'fill="none"/>\n  <a href="#patch/organizations/organization-id/record'
    + '-types/record-type-id/instances/instance-id">\n    <circle class="fil'
    + 'led" cx="154" cy="1672" r="5"/>\n  </a>\n  <a href="#delete/organizat'
    + 'ions/organization-id/record-types/record-type-id/instances/instance-i'
    + 'd">\n    <circle class="filled" cx="194" cy="1672" r="5"/>\n  </a>\n '
    + ' <text class="uri" x="224" y="1675">/api/organizations/:organization-'
    + 'id/record-types/:record-type-id/instances/:instance-id</text>\n  <a h'
    + 'ref="#get/organizations/organization-id/record-types/record-type-id/i'
    + 'nstances/instance-id/versions">\n    <circle class="filled" cx="34" c'
    + 'y="1690" r="5"/>\n  </a>\n  <rect class="empty" x="69" y="1685" width'
    + '="10" height="10" fill="none"/>\n  <rect class="empty" x="109" y="168'
    + '5" width="10" height="10" fill="none"/>\n  <rect class="empty" x="149'
    + '" y="1685" width="10" height="10" fill="none"/>\n  <rect class="empty'
    + '" x="189" y="1685" width="10" height="10" fill="none"/>\n  <text clas'
    + 's="uri" x="224" y="1693">/api/organizations/:organization-id/record-t'
    + 'ypes/:record-type-id/instances/:instance-id/versions</text>\n  <a hre'
    + 'f="#get/organizations/organization-id/record-types/record-type-id/ins'
    + 'tances/instance-id/versions/etag">\n    <circle class="filled" cx="34'
    + '" cy="1708" r="5"/>\n  </a>\n  <rect class="empty" x="69" y="1703" wi'
    + 'dth="10" height="10" fill="none"/>\n  <rect class="empty" x="109" y="'
    + '1703" width="10" height="10" fill="none"/>\n  <rect class="empty" x="'
    + '149" y="1703" width="10" height="10" fill="none"/>\n  <rect class="em'
    + 'pty" x="189" y="1703" width="10" height="10" fill="none"/>\n  <text c'
    + 'lass="uri" x="224" y="1711">/api/organizations/:organization-id/recor'
    + 'd-types/:record-type-id/instances/:instance-id/versions/:etag</text>'
    + '\n  <a href="#get/organizations/organization-id/record-types/record-t'
    + 'ype-id/versions">\n    <circle class="filled" cx="34" cy="1726" r="5"'
    + '/>\n  </a>\n  <rect class="empty" x="69" y="1721" width="10" height="'
    + '10" fill="none"/>\n  <rect class="empty" x="109" y="1721" width="10" '
    + 'height="10" fill="none"/>\n  <rect class="empty" x="149" y="1721" wid'
    + 'th="10" height="10" fill="none"/>\n  <rect class="empty" x="189" y="1'
    + '721" width="10" height="10" fill="none"/>\n  <text class="uri" x="224'
    + '" y="1729">/api/organizations/:organization-id/record-types/:record-t'
    + 'ype-id/versions/</text>\n  <a href="#get/organizations/organization-i'
    + 'd/record-types/record-type-id/versions/etag">\n    <circle class="fil'
    + 'led" cx="34" cy="1744" r="5"/>\n  </a>\n  <rect class="empty" x="69" '
    + 'y="1739" width="10" height="10" fill="none"/>\n  <rect class="empty" '
    + 'x="109" y="1739" width="10" height="10" fill="none"/>\n  <rect class='
    + '"empty" x="149" y="1739" width="10" height="10" fill="none"/>\n  <rec'
    + 't class="empty" x="189" y="1739" width="10" height="10" fill="none"/>'
    + '\n  <text class="uri" x="224" y="1747">/api/organizations/:organizati'
    + 'on-id/record-types/:record-type-id/versions/:etag</text>\n</svg>\n';
